spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hama?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
logging:
  file: ./logs/demo.log