server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hama?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
logging:
  file: ./logs/hamaServer.log
  
management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字